name: CI - Server

on:
  push:
    branches:
      - mark-as-done

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
        working-directory: server
      - name: Build
        run: npm run build
        working-directory: server
      - name: Start
        run: npm start
        working-directory: server
      - name: Test
        run: |
          npm test
        working-directory: server